### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by domehead100** [tom-englert/Wax#6]
Just tried this out with a Solution I'm working on.  This solution is quite large and already has a few setup projects in it.  When I load Wax via Tools -> Wix Setup Editor, I get:

Error loading: System.NullReferenceException: Object reference not set to an instance of an object.
   at tomenglertde.Wax.Model.VisualStudio.Solution..ctor(Solution solution)
   at tomenglertde.Wax.MainViewModel..ctor(Solution solution)
   at tomenglertde.Wax.MainView.Refresh()

**Comment by jenealogy** [comment]
Similar issue -- When I load Wax via Tools > Wix Setup Editor, nothing happens.  Using Visual Studio Professional 2015 v14.0.25425.01 Update 3.  Have installed:
Wax 1.0.14.0 
Windows Installer XML Toolset 3.10.3.3007

**Comment by tom-englert** [comment]
Fixed in v1.0.15.0

**Comment by godadada** [comment]
The issue just re-appeared with v1.0.24.0.

**Comment by tom-englert** [comment]
@godadada this must be st. different, do you have a more detailed call stack?

**Comment by godadada** [comment]
Thanks.  you are so quick.   


Rgds godadada@yahoo.com

**Comment by godadada** [comment]
I still see the issue:

<img width="523" alt="wax fail" src="https://cloud.githubusercontent.com/assets/6087668/25041980/6351484e-20e2-11e7-85ca-01a5de0ee889.png">

**Comment by tom-englert** [comment]
Can you try this debug version:

https://1drv.ms/u/s!Auam3jxFhE-WgYUeErVPWPqv9dsZWw

**Comment by tom-englert** [comment]
What VS-Version do you use?

**Comment by godadada** [comment]
15




Get Outlook for Android









On Fri, Apr 14, 2017 at 9:52 AM -0400, "tom-englert" <notifications@github.com> wrote:












What VS-Version do you use?

**Comment by godadada** [comment]
Rgds godadada@yahoo.com

**Comment by tom-englert** [comment]
@godadada did you have a chance to try the debug version?

**Comment by godadada** [comment]
The last result i sent was from debug version you pointed to me.




Get Outlook for Android









On Tue, Apr 18, 2017 at 8:52 AM -0400, "tom-englert" <notifications@github.com> wrote:












@godadada did you have a chance to try the debug version?

**Comment by godadada** [comment]
<img width="613" alt="wax debug version fail 1" src="https://cloud.githubusercontent.com/assets/6087668/25139679/fc245466-242b-11e7-83df-9715d6095b60.png">
